# set prefix key to ctrl+a
#set -g prefix C-a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'uttarayan21/tmux-wombat'

# Fix for vscode
set -sg escape-time 10

# Reload
bind r source-file ~/.config/tmux/tmux.conf \; run-shell "echo 'tmux.conf reloaded'"

# Split "terminal" pane
bind ` split-window -v -l25%

# Navigate windows
bind-key -n S-left previous-window
bind-key -n S-right next-window

# Initialize TMUX plugin manager (keep this at the very bottom of tmux.conf)
if "[ -x ~/.config/tmux/plugins/tpm/tpm ]" {
    run "~/.config/tmux/plugins/tpm/tpm"
} {
    run -b "\
        echo 'Installing TPM...' && \
        git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm && \
        ~/.config/tmux/plugins/tpm/tpm && \
        ~/.config/tmux/plugins/tpm/bin/install_plugins && \
        sed -i .bak '1s|.*|#!/usr/bin/env bash|' ~/.config/tmux/plugins/tmux-wombat/wombat.tmux && \
        ~/.config/tmux/plugins/tpm/tpm && \
    :"
}

