#!/bin/bash

# Bash history settings
export HISTFILESIZE=10000
export HISTSIZE=20000
export HISTCONTROL=ignoredups:erasedups
export HISTTIMEFORMAT="[$(tput setaf 6)%F %T$(tput sgr0)]: " # colorful date
export HH_CONFIG=hicolor,rawhistory

